"""add invitations

Revision ID: 482c67144f35
Revises: 69aef4c4cce8
Create Date: 2026-07-31 23:18:41.168916

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "482c67144f35"
down_revision = "69aef4c4cce8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("dossier_id", sa.Integer(), nullable=True),
        sa.Column("invited_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["dossiers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invitations_email"), ["email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_invitations_token"), ["token"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invitations_token"))
        batch_op.drop_index(batch_op.f("ix_invitations_email"))

    op.drop_table("invitations")
    # ### end Alembic commands ###
