"""initial schema

Revision ID: 69aef4c4cce8
Revises:
Create Date: 2026-07-31 22:31:42.045805

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "69aef4c4cce8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "dossiers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("alias", sa.String(length=255), nullable=True),
        sa.Column("organization", sa.String(length=255), nullable=True),
        sa.Column("authorization_scope", sa.Text(), nullable=True),
        sa.Column("attested_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dossiers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dossiers_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "org_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "user_id", name="uq_membership_org_user"),
    )
    with op.batch_alter_table("org_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_org_memberships_org_id"), ["org_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_org_memberships_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("dossier_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["dossiers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_logs_dossier_id"), ["dossier_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "dossier_org_access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dossier_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["dossiers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dossier_id", "org_id", name="uq_org_access_dossier_org"),
    )
    with op.batch_alter_table("dossier_org_access", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dossier_org_access_dossier_id"), ["dossier_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dossier_org_access_org_id"), ["org_id"], unique=False
        )

    op.create_table(
        "dossier_shares",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dossier_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["dossiers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dossier_id", "user_id", name="uq_share_dossier_user"),
    )
    with op.batch_alter_table("dossier_shares", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dossier_shares_dossier_id"), ["dossier_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dossier_shares_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dossier_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["dossiers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notes_dossier_id"), ["dossier_id"], unique=False
        )

    op.create_table(
        "scan_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dossier_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("module", sa.String(length=32), nullable=False),
        sa.Column("params", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("message", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["dossiers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scan_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scan_jobs_dossier_id"), ["dossier_id"], unique=False
        )

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dossier_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["dossiers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dossier_id", "name", name="uq_tag_dossier_name"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tags_dossier_id"), ["dossier_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_dossier_id"))

    op.drop_table("tags")
    with op.batch_alter_table("scan_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_jobs_dossier_id"))

    op.drop_table("scan_jobs")
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notes_dossier_id"))

    op.drop_table("notes")
    with op.batch_alter_table("dossier_shares", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dossier_shares_user_id"))
        batch_op.drop_index(batch_op.f("ix_dossier_shares_dossier_id"))

    op.drop_table("dossier_shares")
    with op.batch_alter_table("dossier_org_access", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dossier_org_access_org_id"))
        batch_op.drop_index(batch_op.f("ix_dossier_org_access_dossier_id"))

    op.drop_table("dossier_org_access")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_dossier_id"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("org_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_org_memberships_user_id"))
        batch_op.drop_index(batch_op.f("ix_org_memberships_org_id"))

    op.drop_table("org_memberships")
    with op.batch_alter_table("dossiers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dossiers_owner_id"))

    op.drop_table("dossiers")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("organizations")
    # ### end Alembic commands ###
